# Based on excellent https://github.com/suxue/kernel-test-module example

language: c

env:
    - KERNEL=3.8
    - KERNEL=3.14

before_script:
    - wget https://www.kernel.org/pub/linux/kernel/v3.x/linux-${KERNEL}.tar.gz
    - tar xf linux-${KERNEL}.tar.gz
    - make -C linux-${KERNEL} prepare

script:
    - make -j$JOBS -C linux-${KERNEL} M=`pwd`